name: Issue Labeled

on:
  issues:
    types: [labeled]

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  issue-labeled-blocked:
    name: blocked/* label added
    if: startsWith(github.event.label.name, 'blocked/')
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        id: generate-token
        env:
          RELEASE_BOARD_GH_APP_CREDS: ${{ secrets.RELEASE_BOARD_GH_APP_CREDS }}
        run: |
          set -eo pipefail
          TOKEN=$(npx @electron/github-app-auth --creds=$RELEASE_BOARD_GH_APP_CREDS --org electron)
          echo "TOKEN=$TOKEN" >> "$GITHUB_OUTPUT"
      - name: Set status
        if: ${{ steps.generate-token.outputs.TOKEN }}
        uses: github/update-project-action@2d475e08804f11f4022df7e21f5816531e97cb64 # v2
        with:
          github_token: ${{ steps.generate-token.outputs.TOKEN }}
          organization: electron
          project_number: 90
          content_id: ${{ github.event.issue.node_id }}
          field: Status
          value: 🛑 Blocked
  issue-labeled-blocked-need-repro:
    name: blocked/need-repro label added
    if: github.event.label.name == 'blocked/need-repro'
    permissions:
      issues: write  # for actions-cool/issues-helper to update issues
    runs-on: ubuntu-latest
    steps:
      - name: Create comment
        uses: actions-cool/issues-helper@dad28fdb88da5f082c04659b7373d85790f9b135 # v3.3.0
        with:
          actions: 'create-comment'
          body: |
            Hello @${{ github.event.issue.user.login }}. Thanks for reporting this and helping to make Electron better!

            Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

            Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

            Now adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment. This issue will be closed in 10 days if the above is not addressed.
